[programs.localnet]
spl_token_registry = "Hat4JBCvCMe4NBWPUXo1SU8HH2ppQt2Zpc7DWGwUfvhB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/jbogle/Projects/spl-token-registry/.config/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
